### ISSUE TITLE
Homepage widget help

### ISSUE THREAD

**Issue by kelocke** [lisawilliams/bu550-704#2]
Website design help. We're stuck on how to change the header photo on the homepage, how to make an image post on the website without text, and how to organize posts into sections on the website.

**Comment by lisawilliams** [comment]
Can you post a link?  Both to the page I am supposed to be looking at and to the login page to your site.

**Comment by kelocke** [comment]
http://bujournalism.com/team-three/wp-admin/customize.php?url=http%3A%2F%2Fbujournalism.com%2Fteam-three%2F
Here is the link to customize the site.

**Comment by lisawilliams** [comment]
Okay. Visit the following page: 

http://bujournalism.com/team-three/wp-admin/nav-menus.php

And there, you'll see your three nav headings.  Look at the top one (Storm) and click on it. 
You'll see that I made a fresh post, and added the URL there as a custom link.  

![screen shot 2018-01-25 at 2 08 26 pm](https://user-images.githubusercontent.com/809042/35407235-46d289b6-01d9-11e8-9415-b5f845d013ee.png)

Make the other two nav elements link to the pages with content you want them to go to.

**Comment by kelocke** [comment]
Got it, thank you!

**Comment by lisawilliams** [comment]
Documentation for Juno theme, in case you want to use it again.  It's very full-featured, though, so if you use it again, a thorough read of the documentation would be worth your team's time: https://smartcatdesign.net/kb/setting-juno-theme/
