### ISSUE TITLE
Pointing Reclaim Domain at Wordpress

### ISSUE THREAD

**Issue by jnrice** [lisawilliams/bu550-704#3]
Jordan Rice, 704

https://wordpress.com/domains/add/jnricenet.wordpress.com (might be WordPress login protected) 
I am trying to get Wordpress to use the domain name I bought on Reclaim Hosting, www.jnrice.net

I followed the instructions as seen here: https://community.reclaimhosting.com/t/domain-mapping-to-wordpress/879

But when I get to step 4 it asks me to pay for WordPress premium which is $96. Is there something that I am missing to not pay the extra money? 

I googled around more but did not find any additional info on this.

**Comment by lisawilliams** [comment]
So Jordan -- I saw the recent note on this, pointing to this knowledgebase article: https://community.reclaimhosting.com/t/installing-wordpress/265

Did this solve the problem? Are they still asking you to pay?

**Comment by jnrice** [comment]
Here is the link that helped me connect my reclaim domain to WordPress!
https://community.reclaimhosting.com/t/installing-wordpress/265

**Comment by lisawilliams** [comment]
Thanks for tying up your issue, Jordan! Good work. 👍
