### ISSUE TITLE
Making Header Image Span Entire Width of Page-JO704

### ISSUE THREAD

**Issue by jrochele** [lisawilliams/bu550-704#4]
Section: JO704	
URL of problem: http://www.nobrainersite.com/

--My site banner/header image does not fill the width of the page, as you can see in my screenshot. I have been trying to alter its width by tinkering with the CSS code in “customize” mode, but I have not been able to change this. 
--Specifically, I tried to alter the size of the image specified within the code. 
--I have also tried resizing the image to make it bigger but that does not work either. 
--I have tried googling how to fix this issue by coding, and most of what I have found says that I need to make the header image width “100%” --which I have done and also does not work. 
--I also tried using a different image and had the same problem. 

![issue1](https://user-images.githubusercontent.com/36112904/35771838-0ca07b52-0901-11e8-8a59-a82645672802.JPG)

**Comment by lisawilliams** [comment]
Okay, can you tell me the name of the theme you are using?

**Comment by lisawilliams** [comment]
One more question: I remember you showing me this site. Did it work at one time, or is this new behavior?

**Comment by jrochele** [comment]
The theme I’m using is called di blog. When I showed you my site I was originally using one of the default themes, the 2017 one. Since I’ve been working with this theme, di blog, today, I have not been able to get the header to work properly. It works on mobile and tablet views just fine, but not on desktop.

**Comment by lisawilliams** [comment]
Okay, great. I'm going to install that template on one of our sandbox sites and play with it a little bit. The other recommendation/question I have: does this theme have documentation?  For example, here's the documentation for Voice, the theme used for bunewservice.com: https://mekshq.com/documentation/voice/

**Comment by lisawilliams** [comment]
OK -- check this out: http://bujournalism.com/test-header/

When you log into your blog and visit Customize > Header Image with the di blog theme, it says: 

```

Click “Add new image” to upload an image file from 
your computer. Your theme works best with an 
image with a header size of 1140 × 260 pixels — 
you’ll be able to crop your image once you 
upload it for a perfect fit.

```
Now, it looks to me like your current blue header image is larger than 1140 x 260, so I was thinking it *should* work, but clearly it doesn't. 

So I used Google Advanced Image Search (https://www.google.com/advanced_image_search) to find images larger than 1024X768, and found the following header image: http://www.articque.com/wp-content/themes/articque/images/backgrounds/header/art-header-main/full/r_atr-header-main.jpg.  This is bigger than your current header image.  I uploaded it, and voilá, it worked.  Try it out yourself. Using advanced image search, you can search for images large enough. Be sure to scroll down and filter by license to find something that is copyright-free or Creative Commons licensed.

**Comment by jrochele** [comment]
Thank you for your help!

Jacqueline Rocheleau
Boston University
B.A. Neuroscience and Psychology
M.S. Science Journalism, September 2018
jrochele@bu.edu | 774-364-1960

**Comment by jrochele** [comment]
It turns out the problem was the image I was using. Despite the fact that my image was larger than the required dimensions, it was not filling the space. I followed @lisawilliams ' advice and just searched for a different image larger than the required dimensions.
