### ISSUE TITLE
How to Limit a "New Post" to One Menu Section

### ISSUE THREAD

**Issue by hugh24e** [lisawilliams/bu550-704#5]
When I add a "new post" to my webpage it automatically places that post on the Home page and nowhere else. I added a NewsTracker section on my main menu and would like my NewsTracker posts to show up there (as individual POSTS and not just a constant stream of text like I get with "edit page").

Is there a way to specify where a "new post" goes?

Thanks!

Emily

**Comment by lisawilliams** [comment]
Emily, can you leave me a link to your blog, and give me the name of the theme you are using?

**Comment by hugh24e** [comment]
http://ephughes.com/

And I'm using Twenty Eleven. 

I put the beginning of my News Tracker post in that section so you can kind of see what I mean. It's all one page instead of it's own individual post.

**Comment by lisawilliams** [comment]
Okay, great.  

I think for you the answer is to have a site with a static front page. In fact, your front page could be an About page, or list the clips/segments you're the most proud of, etc. 

To do that, you need to use a theme that supports it.  Read this first: http://www.wpbeginner.com/glossary/static-front-page/

Once you're finished reading, log in to Wordpress and go to Appearance > Add Themes, and at the top of that page you will see a button above the themes that says 'Add New.'  Click that and then just enter the word 'Static' in the search box. You'll see plenty of themes that support a static front page.  

Once you've done that, you'll need to set up your menu. I recommend having menu items link to two types of things: 1) Static pages or 2) a category. You may want to make a News Tracker category, put a few example posts in it, and then link to the category page in the menu.

**Comment by lisawilliams** [comment]
PS if you do this and then you have questions about setting up the menu...file a new issue because Only One Issue Per Issue! 😀 https://github.com/lisawilliams/bu550-704#one-issue-per-issue

**Comment by lisawilliams** [comment]
Oh, and when you're choosing a theme, if you don't see it immediately, google '(theme name) documentation.' A theme that has ongoing support and is well-done will have pretty extensive documentation. It's worth your time to read it, if you're going to be working with that theme for awhile.
