### ISSUE TITLE
Log In Issues with ReclaimHosting & WordPress

### ISSUE THREAD

**Issue by mrumore** [lisawilliams/bu550-704#6]
**Section:** JO704
**URL:** meredithrumore.com
**Issue Description:** Can't log into my WordPress account, both through Reclaim and through WP itself.
**What Happened:** Yesterday, I downloaded the WordPress application in my Reclaim hosting channel, which automatically set up a WP account for me, accessible through my Reclaim account. When I logged into Reclaim to access my WP account this morning, the WP application was completely uninstalled. My WP website still exists, but I can't log into it. I tried to log in through WP with my Reclaim information, but according to WP, there's no account attached to that address which I know is false.

I googled the issue and found very little help. It almost seems like no one else has had this problem before but I can't imagine that's true. I have no idea what mistake I made. HALP!

**Comment by lisawilliams** [comment]
OK, Meredith -- you and I spoke and I know you filed a support ticket with Reclaim. We'll wait for word from them but you and I will also meet after class today to get to the bottom of this.

**Comment by mrumore** [comment]
The issue was solved by scratching the whole site and starting over again. Oh well! :[
